name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: github-action-timing
        uses: ./
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1